### ISSUE TITLE
what is the version of ffmpeg,  version like this:  4.1

### ISSUE THREAD

**Issue by lutaooooo** [mcmtroffaes/ffmpeg-msvc-build#3]
what is the version of ffmpeg,  version like this:  4.1

**Comment by mcmtroffaes** [comment]
It's the latest from git as per the tag date.

**Comment by ValZapod** [comment]
Do you know some commits like https://github.com/FFmpeg/FFmpeg/search?o=desc&q=msvc&s=committer-date&type=commits 

that help msvc? e.g. very recent https://github.com/FFmpeg/FFmpeg/commit/c0cf2c47864bde4db155909e77436008654fef27 helps

 src/libavfilter/vf_ssim360.c(549): error C2099: initializer is not a constant
