### ISSUE TITLE
is libx264 enabled? avcodec_find_encoder_by_name("libx264"); return NULL

### ISSUE THREAD

**Issue by lutaooooo** [mcmtroffaes/ffmpeg-msvc-build#4]
is libx264 enabled? avcodec_find_encoder_by_name("libx264"); return NULL

**Comment by mcmtroffaes** [comment]
The release builds are LGPL (to allow use also in non-GPL projects), and x264 is not LGPL, so no it's not included in the release. However you can build it yourself quite easily with vcpkg if you enable the option. Even though it's not included with the binary release, the x264 feature is tested in the test suite and so is expected to work. I hope this helps!
