### ISSUE TITLE
Build options and features static link

### ISSUE THREAD

**Issue by Instand** [mcmtroffaes/ffmpeg-msvc-build#7]
Hello! I have some questions.
- ffmpeg build includes do not contain deprecated api. Can i build ffmpeg with "enable-deprecated" or something like that.
- All ffmpeg libs have shared linkage. I want to have features  static link to avcodec.dll. For example to link libx264.dll, libx265.dll staticly to avcodec.
Big thanks in advance!

**Comment by Instand** [comment]
I found that ffmepg 4.4 does not contain deprecated apis. I try to change local vcpkg.json version to 4.2.4 (it has deprecated apis), but vckpg downloads the last version anyway. "builtin-baseline" by commit does not work same

**Comment by mcmtroffaes** [comment]
If you want an old ffmpeg, I suggest cloning vcpkg directly and checking out an old commit matching the version you need. The updates are listed in the commit messages of vcpkg so it should be possible to figure out which commit to use. The last 4.2 release appears to be here: https://github.com/microsoft/vcpkg/commit/d548c6774403ac1b48ca1a480776c43dd085ca09

Mixed linkage in vcpkg is in principle possible but there's no easy way to "cherry-pick" which libraries should be static and which dynamic. It's either all static or all dynamic (although individual ports sometimes override the default choice if need be, but only if no other linkage is supported). I don't recommend trying this although I think for some libraries you might be able to make this work. It's definitely not officially supported by vcpkg and I also have no intention to support it. If you want static linkage, basically everything needs to be static, including all of ffmpeg's libraries.

I'm so sorry that I can't be more helpful!

**Comment by Instand** [comment]
Checking out to https://github.com/microsoft/vcpkg/commit/d548c6774403ac1b48ca1a480776c43dd085ca09 helped with deprecated features.
I understood about static/dynamic linkage, i will prefer dynamic linkage for all libraries.
Thanks for your help.

Best regards,
Nikita

**Comment by mcmtroffaes** [comment]
Sure, glad I could at least point you to the relevant vcpkg commit for the older version. Good luck!!
